## This code creates an update trianing data set 
## from the files generated by the matching app

## v1: initial version of household comprisons which follows blocking procedure

library(tidyverse)
library(here)

# load functions for calculating matching variables
for(a in list.files(here("R", "functions"), full.names = T)){
  source(a)
}

# load file containing household members of training cases
for_rosters <- read_csv(here("data", "for_rosters.csv")) %>% 
  mutate(namefrst = if_else(is.na(namefrst), "", namefrst),
         namelast = if_else(is.na(namelast), "", namelast))

# combine coded training files
full_data <- load_training_data(here("data", "Training"))

# write file for training models
write_csv(full_data, here("data", "training_all_vars_v3.csv"))
