## This code creates an update trianing data set 
## from the files generated by the matching app

## v1: initial version of household comprisons which follows blocking procedure

library(tidyverse)
library(here)

# load functions for calculating matching variables
source(here("R", "functions", "add_matching_vars.R"))
source(here("R", "functions", "compare_hh_rosters.R"))
source(here("R", "functions", "load_training_data.R"))
source(here("R", "functions", "unabbv_names.R"))

# load file containing household members of training cases
for_rosters <- read_csv(here("data", "for_rosters.csv")) 

# combine coded training files
full_data <- load_training_data(here("data", "Training"))

# overwrite previous file
write_csv(full_data, here("data", "training_all_vars_v1.csv"))
